name: Phonix Test Automation Workflow

on: 
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "17 10 * * *"
    - cron: "30 17 * * *"
    - cron: "12 10 * * *"
    
  workflow_dispatch:
    inputs:
      env:
        description: "Enviroment"
        type: choice
        options: [qa,uat,dev,live]
        default: qa
        required: true
      suiteXmlFile:
       description: "suiteXmlFile"
       type: choice
       options: ['testng.xml', 'Regression.xml','P1Test.xml']
       required: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.1

      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Execute Test Automation Framework
        run: mvn test -DsuiteXmlFiles="${{github.event.inputs.suiteXmlFile}}" -Denv="${{github.event.inputs.env}}"

      - name: Upload SureFire Report Artifact
        if: always()
        uses: actions/upload-artifact@v5.0.0
        with:
          name: SureFire Report
          path: target/surefire-reports/
          retention-days: 10
